[package]
name = "esp-32-img-server"
version = "0.1.1"
edition = "2021"

[dependencies]
axum = { version = "0.7.4", features = ["macros"] }
serde = { version = "1.0.192", features = ["derive"] }
chrono = "0.4.31"
rand = "0.8.5"
tokio = { version = "1.0", features = ["full"] }
